# Generated by Django 4.1.3 on 2022-11-28 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('address', models.TextField(blank=True, max_length=128)),
                ('contact', models.TextField(blank=True, max_length=128)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parser_hh.city')),
            ],
        ),
        migrations.CreateModel(
            name='Employment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('description', models.TextField(blank=True)),
                ('requirement', models.TextField(blank=True)),
                ('responsibility', models.TextField(blank=True)),
                ('role', models.CharField(blank=True, max_length=64)),
                ('url', models.CharField(blank=True, max_length=64)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parser_hh.company')),
                ('employment', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='parser_hh.employment')),
                ('experience', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='parser_hh.experience')),
                ('salary', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='parser_hh.salary')),
                ('schedule', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='parser_hh.schedule')),
                ('skill', models.ManyToManyField(blank=True, to='parser_hh.skill')),
                ('specialization', models.ManyToManyField(blank=True, to='parser_hh.specialization')),
            ],
        ),
        migrations.CreateModel(
            name='Param',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_words', models.CharField(max_length=64)),
                ('salary', models.CharField(blank=True, max_length=8, null=True)),
                ('city', models.CharField(blank=True, max_length=8, null=True)),
                ('experience', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='parser_hh.experience')),
                ('schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='parser_hh.schedule')),
            ],
        ),
    ]
