# Generated by Django 4.1.3 on 2022-11-29 10:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('parser_hh', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='param',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
