# Generated by Django 4.1.3 on 2022-12-01 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parser_hh', '0004_rename_user_param_author_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vacancy',
            old_name='user_vacancy',
            new_name='author',
        ),
    ]
