# Generated by Django 4.1.3 on 2022-12-01 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parser_hh', '0010_alter_vacancy_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='param',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='parser_hh.param'),
        ),
    ]
