# Generated by Django 4.1.3 on 2022-12-01 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parser_hh', '0011_vacancy_param'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='param',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parser_hh.param'),
        ),
    ]
