# Generated by Django 4.1.3 on 2022-12-04 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_hh', '0012_alter_vacancy_param'),
    ]

    operations = [
        migrations.AddField(
            model_name='param',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
